# Generated by Django 5.0.6 on 2024-06-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('priority', models.SmallIntegerField(choices=[(0, 'Low'), (1, 'High')], default=0)),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
    ]
